ManuelGil/Hacktoberfest

docs/index.html

Added JuneBug font and basic HTML document structure.

Add JuneBug font

---

src/SortingAlgorithms/Python/bubbleSort.py

Added a Bubble Sort algorithm in Python.

Add Bubble Sort in Python

---

README.md

Added my info to README.md. Farewell my firend! 😊

Add my info to README.md

---

docs/index.html

Reference issue: https://github.com/ManuelGil/Hacktoberfest/issues/5
How about Georgia font?  :)

Update index.html with Georgia font.

---

LICENSE

Added MIT license :)

---

src/Java/HelloWorld.java
src/Python/helloworld.py

Added "Hello World" in python and java programming languages

Hello World in Python and Java

---

src/C++/hello_world.cpp

Add C++ hello world

---

src/Perl/hello_world.pl

Perl hello world implemented

---

README.md

added trustjamin to the README.md file

Added self as a contributor

---

src/octave/hello_world.m

added hello world program in octave, in response to #8

hello world in Octave

---

src/SortingAlgorithms/java/BubbleSort.java
src/SortingAlgorithms/java/BucketSort.java
src/SortingAlgorithms/java/CountingSort.java
src/SortingAlgorithms/java/MergeSort.java
src/SortingAlgorithms/java/QuickSort.java
src/SortingAlgorithms/java/SelectionSort.java

BubbleSort
BucketSort
CountingSort
MergeSort
QuickSort
SelectionSort

added sorting algorithms in Java

---

src/Haskell/hello.hs

added hello world program in Haskell, in response to #8

Add hello world in Haskell

---

src/Elexir/hello.exs

From issue https://github.com/ManuelGil/Hacktoberfest/issues/8

Adding hello world to elixir

---

src/javascript/hello_world.js

for https://github.com/ManuelGil/Hacktoberfest/issues/8

Create "Hello, World!" in javascript

---

src/Dart/hello_world.dart

Added code for hello world in dart language.

add hello_world for dart

---

src/Java/InsertionSort.java

Code for sorting an array using insertion sort in java

Created InsertionSort.java

---

src/Java/FirstPull.java

first pull

---

src/SortingAlgorithms/c++/QuickSort.cpp

Implementation of quick sort in C++ with explanation.

Quick Sort

---

src/Hodor/hodor.md

Add `hello world` program in [Hodor](http://www.hodor-lang.org/)
New language for #8

[hodor] Add `hello world` in Hodor-lang

---

src/Bash/backupuser.sh

Hello, this script serves to make backups of the /home of the users of linux

my contribution

---

src/JS/hanoi-tower.js

Add a Hanoi tower recursive algorithm by Javascript.

Add Javascript HanoiTower Algorithm

---

src/Haxe/HelloWorld.hx

Adding Hello World in Haxe for issue #8

Add hello world in Haxe

---

README.md

This change adds my name to the contributor list

Adding to the list

---

docs/index.htm

This change is to add new fonts Arial, Helvetica to index.htm

Add new fonts Arial, Helvetica to index.htm

---

src/Lua
src/Lua/Hello_World.lua
src/Lua/Lua

I added Lua hello world and moved existing Lua file into Lua folder.

Lua HelloWorld

---

src/Scala/quicksort.scala

Quicksort implemented in scala

Scala quicksort

---

src/Python/helloworld.py

This program has all the necessary changes to run successfully on all versions of python.

HelloWorld  in python having necessary changes

---

src/Racket/helloworld.rkt

Add Racket hello world

---

docs/index.htm

Changed page title to Hacktoberfest 2018

Updated index.htm

---

README.md

Changes to be committed:
modified:   README.md
Untracked files:
src/Java/RecursiveBubbleSort.java

 On branch add_java

---

README.md
src/javascript/helloWorld.js

add hello world in javascript

---

src/JS/insertionSort.js

JS_InsertionSort

---

src/JS/SelectionSort.js
src/JS/insertionSort.js
src/PHP/InsertionSort.php
src/PHP/SelectionSort.php

Php selection sort edit

---

src/JS/SelectionSort.js
src/JS/insertionSort.js

Js selection sort

---

src/JS/SelectionSort.js
src/JS/insertionSort.js
src/PHP/InsertionSort.php

Php insertion sort edit

---

src/Julia/hello_world.jl

Hi, I added hello world example in Julia language.

add Hello World example in Julia

---

src/Java/MyFirstPullRequest.java

Completed my first pull request

Completed my first pull request

---

InsertionOpt.java
src/Java/InsertionOpt.java

Added Optimized Insertion Sort.
Sorts a sequence of strings from standard input using an optimized
version of insertion sort that uses half exchanges instead of 
full exchanges to reduce data movement.

Added Optimised Insertion Sort

---

src/objective_c/main.m

objective c

---

src/C++/insertionsort.cpp
src/Java/linear_search.java

Linear search searches for an entered element in the given array by individually matching every element of the array with the entered element.

Added file for linear search in Java

---

src/Java/MergeSort.java

Add validations in MergeSort Java

Add validations in MergeSort Java

---

README.md
src/javascript/quick_sort.js

hallo i have to add quicksort.js ^_^

addd quick sort js

---

src/C++/heapsort.cpp

Added Heapsort in C++

---

README.md
src/C/simple_list_order_insertion.c

algorithm of ordering in a simple list

added simple list order insertion

---

zigzag-array.java

file contains solution for leetcode problem nu. 6, zigzag-array in java8.

added file zigzag-array.java

---

src/Haskell/insertion_sort.hs

Added insertion sort algorithm in haskell

Added insertion sort in haskell

---

src/Java/UndoHashMap.java

Special hashmap that lets you remove the last entered element

Add hashmap that keeps track of the last element entered

---

docs/index.htm

Added Courier to the font family.

Update index.htm with Courier

---

src/Dart/bubbleSort.dart

Add bubble sort algorithms in Dart

---

src/C++/Quick_sort.cpp

Adding Quick-sort algorithm in C++ programming language.

Add Quick Sort in C++

---

README.md

hacktober3_edits

---

src/Python/segmentTree_min.py

added segment tree (range minimum query) in python

added segment tree (range minimum query)
